
[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "@lej@ndroPortill@30122023"
client_id = "695103885588-7aaumaei19fg94s4rjj97sh50p5rucg2.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"


[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1qHmipZ-xpdWvrQhazuofnzdU7mtph-9x7ngqltMpz8U/edit?gid=0#gid=0"
# From your JSON key file
type = "service_account"
project_id = "rugged-research-461115-j0"
private_key_id = "5db53c6905a14fa4241e9efe8618494e46da5fca"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDMgC+QAO04HnN4\ngi6R/ZqjneAC9Cc6Y98t1zRbAT57q1+wTDrQ32iiMmDFxGH/rOJT9szQu2+A14vz\nie5V+Qav2Fwh4aLec5Zs+RWERsge2E99m8V+RRBOLffRtmtuLcjEbki7jUdpW482\nOCLtQKhDI0PWpvwPQG+H/RPq84qpFgk8jn7QW+oXpyrFjc6nS9XSrTbnYdcLUbKf\nijPyIs7g5zTO/IpI26L3YvodTajHJF585zrCKJG0N40cZNKqvX1Xw+Bal91JDPHf\nGy7f2v4CRJyizyYl/A6L4JbxxY4SoYgWd3Ue/xSDneqQMdPNKMbEjN4i2M4pbyhn\npA7Uhcw3AgMBAAECggEADRssBoPLWueMs/eilMWsQE8xGPoH0j9YrCnuLOTurw4D\n0xss68+y94ODXeQLpHoH2U9oafo77QXOGNzJUxDjg6fko7aVHGz2V46RI/SbWmq3\nkXpxv6QdJZLe8+hH3fxThnn2RwWIwvD/bn9OMbwNQfGZJUEiHLd0Tm1YS5xcfHXp\nHW9o3Eoq56127sUgE06pc1+AvkR9+X4IQoKNb2ZcHFNLfQrYbT0UyS9651phEMNX\nGzdYu3ynLtEfdABGktWi7KA0OEx6IhP4IKOzJJ45TbswXvWPdWLpLTGGnV2riok7\nx6PfGW1umJ0AYZBfM6aSCw0ITJ1Ji8vMzUA1fGbbYQKBgQD8Spx0rih/tOxURm/w\nYfjrWsB00jDdGvlLW3v3o47jZY5kDkaqcj4r3XIHLDr4kLoheOsw+f6vheSCHVOq\nZDJ7loEdtqX7hrdNee4erOLYPOpDpKjWnVKg32cNUBLZ03VVsoKhEIezgFMEnvpD\nW2Mn2m91lFlMek7LZUvI9fgIYQKBgQDPgbwus5r8+DeygvkqXFvRteIgHLGysw9J\n59wjVzb4c+/mxABwOUMa/VwajyZZg0Ihjd3KM26viIrLs9IMm5NhwWUqcrxu0w8e\n5eR+yzMxSHTs/ZXApmnSw1bHATMPalQrwS4luK1mRak/xLKv8atEthmBsIXv6suw\nDOYO/1q7lwKBgQCUnC6E3IGmmCANlGAjrNI/cHmlVprJ4zWtmfnv6Twl3pB9h5tA\nk4Lju9GLQBaMjFPXm66ObvQC2E++BSBfYh4KhqEPq6MiAjy/Om91SkllLpyfs8Jw\niMM/V9kQEnbIMLMRA9HGpkIJDjHYqvyn6JEDzLuS+wuO7Qy06ro1ag3sgQKBgCAj\nMafx/SEMuGOXUUu0Piw+hSUADK1megmyNS/sBAF6wz70QDUhSTlW3/rlDMV0RLu5\now375TqeZRCjava06aCMOUTXvENVwNPCOx9ADU+mryU9KQJLQ7x2sGvlzainiR21\nr5X8Ai8CvvG3Xw1M2n+rzEt/sV60+JLtjHvqJH1FAoGAdaAgeX6RS7fNocda2Fd2\nasiNam5zeOZ7nAOhtXSscA0d5772YuzqNcKdEe2m0lNIEJzywVuzJbDfZCC0c4aZ\nRMSqIshkmTJwXuQoD8Jt6BPDaSjFq7ir10EpQH9Tcy1TZ+MudfuekLEoKTNhlEum\n5LyWlfBfX340gNwh+EA/y5s=\n-----END PRIVATE KEY-----\n"
client_email = "costos@rugged-research-461115-j0.iam.gserviceaccount.com"
client_id = "100067174881601745261"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/costos%40rugged-research-461115-j0.iam.gserviceaccount.com"

